### ISSUE TITLE
Timeout when fetching StarRail information

### ISSUE THREAD

**Issue by blobnom** [PaiGramTeam/SIMNet#24]
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/c348e7e8-c67e-4343-a4f6-9aa7bd5af4b0)
I'm trying to fetch StarRail user information but it seems to time out on every attempt. Thought it was a problem with the cookies I've provided, but even with every existing cookie provided it doesn't work. Any ideas?

**Comment by luoshuijs** [comment]
It looks strange. Could you provide the code you used with `StarRailClient`? Also, could you provide a more detailed traceback? The traceback will provide you with more specific Timeout types, such as `httpx.ConnectTimeout`, `httpx.ReadTimeout`, `httpx.WriteTimeout`, etc.

**Comment by blobnom** [comment]
For now I'm just using the example code from the README 
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/a0cecf4c-5038-42a2-8f39-d101dd50590f)

As for the traceback, here you go
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/eb06f115-102e-49a0-8cab-63b75e4e18fe)
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/9530d5a6-b37d-4211-94ad-dd50cd664102)
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/7fbbc4ab-4a9a-4871-ae9f-1fcb4acba82e)

**Comment by karakoo** [comment]
> For now I'm just using the example code from the README 
> ![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/a0cecf4c-5038-42a2-8f39-d101dd50590f)
> 
> As for the traceback, here you go
> ![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/eb06f115-102e-49a0-8cab-63b75e4e18fe)
> ![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/9530d5a6-b37d-4211-94ad-dd50cd664102)
> ![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/7fbbc4ab-4a9a-4871-ae9f-1fcb4acba82e)
> 

I think this may be a problem with your network.

![IMG_20230516_164228_234.jpg](https://github.com/PaiGramTeam/SIMNet/assets/70872201/3423c128-7712-41d7-93bb-eb4dac70e915)

You can try using the PING command on the domains of these two APIs to check if your network connection is working properly.

**Comment by blobnom** [comment]
Pinging appears to work just fine. Do you other ideas what could cause this issue?
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/9600563a-1083-4ec7-83cd-0fa7b17a78a0)

I don't know if that helps but when I was using the Genshin client everything worked fine

**Comment by blobnom** [comment]
I've tried raising the timeout to 120 seconds to see if that works and after about 20 seconds I got a response.
Unfortunately it's a bad request so I'm curious whether I'm missing some cookie or did something wrong?
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/0339116e-8e7c-4073-ba0b-2bbca97a35e9)
![image](https://github.com/PaiGramTeam/SIMNet/assets/58641892/11ac54a4-8fd5-400a-994e-1a82d5de94f6)

**Comment by luoshuijs** [comment]
I can't determine from the information obtained by pinging whether this is a server connection issue (it's normal for the second domain located in China to timeout), it seems that the connection is normal.
Recently, one of our developers encountered a similar problem during testing. When I ran the tests, everything was normal, possibly because my account is based in China. However, this also suggests that there are no issues with the Client's code structure, making it difficult to determine in the short term whether the issue is with the Client's code or the server side.
However, you can still reduce such problems by setting a timeout. However, it's not recommended to set it too long. Our default timeout is as follows.
https://github.com/PaiGramTeam/SIMNet/blob/39082b4bcd19c2273492682888746fba19f0ce02/simnet/client/base.py#L64-L70
The method `httpx.TimeOut` accepts four parameters to control the timeout.
https://www.python-httpx.org/advanced/#timeout-configuration

**Comment by luoshuijs** [comment]
Based on the error message, I'm unable to determine the cause of this issue, but what I can confirm is that this is not a problem with the cookies. To the best of my knowledge, Hoyolab has not integrated many queries, such as retrieving a list of characters (although such queries do exist in the official Chinese community). Despite this, we will do our best to find the cause of the problem.

**Comment by luoshuijs** [comment]
Since I don't have an international Hoyolab account, I'll reach out to another team member, @Billyzou0741326, to see if he can help identify the problem.

**Comment by luoshuijs** [comment]
Something seems off, I suspect that Hoyolab may not be able to fetch Starrail player information via the `request_game_record` function. If you are only retrieving Starrail user information under the current account, I recommend using the `get_game_accounts` function to obtain all player information associated with that account, and then extract the Starrail player information from there.

**Comment by Billyzou0741326** [comment]
Hi @blobnom, huge thanks for bringing this issue to our attention. I can confirm that the Timeout issue was reproducible on my end.

Your suspicion was correct @luoshuijs that this was due to StarRail has not yet implemented their Battle Chronicle yet.

@blobnom for now, we'll have to rely on `get_game_accounts` to get (less useful) details with regards to HSR. We expect the other endpoints to work if/when HoyoLab decides to implement Battle Chronicle for HSR.

**Comment by blobnom** [comment]
> Your suspicion was correct @luoshuijs that this was due to StarRail has not yet implemented their Battle Chronicle yet.
 
Alright, that makes a lot of sense. Thank you very much for the help and information and have a great day!

**Comment by luoshuijs** [comment]
@blobnom Hsr Battle Chronicle is available in the international server community, and you can try requesting specific information now

**Comment by blobnom** [comment]
Thanks for the information, it works perfectly fine! 😄
